commandsPostDeploy:
  - id: 342f7322-643e-481a-a5ed-ea999ba8ea18
    label: Backfill Crew Size on existing installations
    type: apex
    command: ""
    parameters:
      apexScript: scripts/apex/backfill-crew-size.apex
    runOnlyOnceByOrg: true
    context: process-deployment-only
